---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyapp
  labels:
    app: tinyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyapp
  template:
    metadata:
      labels:
        app: tinyapp
    spec:
      containers:
      - name: tinyapp
        image: quay.io/siamaksade/tinyapp:latest
        ports:
        - containerPort: 8080
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VERSION
            value: v1
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 3
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tinyapp
  name: tinyapp
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: tinyapp
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: tinyapp
  name: tinyapp
spec:
  to:
    name: tinyapp